name: Run Checks on PR

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install test dependencies
        run: npm ci

      - name: Use local action
        uses: ./
        with:
          version: 'v3.3.5'

      - name: Verify Tailwind installation
        run: |
          tailwindcss -v
